fixed a serious problem when capka.jar is not part of the classpath causing java.lang.NoClassDefFoundError exceptions preventing conformer or property calculations.